### PR TITLE
feat(guest): add support for `open` on `/etc/resolv.conf`

### PR DESCRIPTION
**Pull request by rvolosatovs**
Required for https://github.com/enarx/enarx/pull/1500

### CODE REVIEW

**Comment by rvolosatovs** [comment]
Do we want to check the flags and enforce read-only access?

**Comment by haraldh** [comment]
Filtering by pathname should happen in the shim not in the host.

**Comment by rvolosatovs** [comment]
As a precaution I added it in both

**Review by haraldh — APPROVED** [review]

**Comment by npmccallum** [comment]
@rvolosatovs Do tests normally take this long?

**Comment by haraldh** [comment]
> @rvolosatovs Do tests normally take this long?

I rekicked them... github had hickups lately.

**Comment by haraldh** [comment]
> @rvolosatovs @haraldh
> 
> ```
> test integration_tests::syscall::sendto has been running for over 60 seconds
> test integration_tests::syscall::sync_read_close has been running for over 60 seconds
> ```

must be the github docker context... worksforme locally...

**Review by haraldh — APPROVED** [review]

**Pull request merged**
